package com.example.umatsu.trainingCRUD.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectProvider;

import com.example.umatsu.trainingCRUD.form.SelectMemberForm;
import com.example.umatsu.trainingCRUD.mapper.provider.MySelectProvider;
import com.example.umatsu.trainingCRUD.model.TbMember;
import com.example.umatsu.trainingCRUD.model.TbMemberExample;

public interface TbMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_MEMBER
     *
     * @mbggenerated Sun May 14 18:27:59 GMT+09:00 2017
     */
    int countByExample(TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_MEMBER
     *
     * @mbggenerated Sun May 14 18:27:59 GMT+09:00 2017
     */
    int deleteByExample(TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_MEMBER
     *
     * @mbggenerated Sun May 14 18:27:59 GMT+09:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_MEMBER
     *
     * @mbggenerated Sun May 14 18:27:59 GMT+09:00 2017
     */
    int insert(TbMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_MEMBER
     *
     * @mbggenerated Sun May 14 18:27:59 GMT+09:00 2017
     */
    int insertSelective(TbMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_MEMBER
     *
     * @mbggenerated Sun May 14 18:27:59 GMT+09:00 2017
     */
    List<TbMember> selectByExample(TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_MEMBER
     *
     * @mbggenerated Sun May 14 18:27:59 GMT+09:00 2017
     */
    TbMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_MEMBER
     *
     * @mbggenerated Sun May 14 18:27:59 GMT+09:00 2017
     */
    int updateByExampleSelective(@Param("record") TbMember record, @Param("example") TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_MEMBER
     *
     * @mbggenerated Sun May 14 18:27:59 GMT+09:00 2017
     */
    int updateByExample(@Param("record") TbMember record, @Param("example") TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_MEMBER
     *
     * @mbggenerated Sun May 14 18:27:59 GMT+09:00 2017
     */
    int updateByPrimaryKeySelective(TbMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_MEMBER
     *
     * @mbggenerated Sun May 14 18:27:59 GMT+09:00 2017
     */
    int updateByPrimaryKey(TbMember record);
    
	/** 自作
	 * @param form
	 * @return
	 */
	@SelectProvider(type=MySelectProvider.class, method = "findBy")
	List<TbMember>findMember(@Param("selectMemberForm") SelectMemberForm form);

}